### ISSUE TITLE
Define dataset in batch processing mode

### ISSUE THREAD

**Issue by msphan** [PreibischLab/BigStitcher#13]
Hi,
Thanks for your great effort of big stitching. I'm trying to switch to "batch processing" mode. However, it seems that the option "Move Tiles to Grid (Interactive)" in the step "Define Dataset" doesn't work. In addition, the option "Read locations from file" is not available in "batch processing" mode.

**Comment by hoerldavid** [comment]
Hi @msphan,

True, 'Move Tiles to grid (Interactive)' does not work in batch mode (since it tries to interactively preview the transformations) - we could add a notification to clarify that.
For that reason, we also offer 'Move Tiles to grid (Macro-scriptable)' in the same drop-down menu, which offers the same parameters but no live preview. As the name implies, this should work in batch mode (let us know if it doesn't).

Regarding "Read locations from file": we simply did not implement that in batch mode yet. This should be no big problem, however - I'll try to add it in one of the next updates.

Hope this helps!
All the best,
David

**Comment by msphan** [comment]
Hi David,

Assume 3 x 2 x 2 image tiles in x, y and z respectively (e.g. tile id from 1 to 12). Using "Move Tiles to grid (Interactive)" with "Snake: Right & Down", the result is exactly what I expect, so that the tiles 1-6 is above tiles 7-12 in z. However, the z direction seems to be inversed when using "Move Tiles to grid (Macro-scriptable)" and 1-6 is below 7-12... The only thing I can do is to change tile id...

Regards,
Son

**Comment by hoerldavid** [comment]
Hi Son,

That should not happen, obviously. I had a quick look and it seems that it is indeed a bug in my code - I'll try to fix it (and add the batch 'Read locations from file') as soon as possible. 

David

**Comment by alonyan** [comment]
Just adding a +1 to the feature request ('Read locations from file'). Thanks a lot for all of your hard work, it runs great!

**Comment by hoerldavid** [comment]
Hi @msphan,

I had a look on the grid definition code and "Move Tiles to grid (Macro-scriptable)" was indeed broken in a fundamental way :(
I fixed it with https://github.com/PreibischLab/multiview-reconstruction/commit/456e7b81286123dd83e610682fb2cd4b056dd652 (the update should be available in Fiji already)

This might solve your problem of different behavior in macro and interactive mode as well - please let me know if the problem persists!

David

**Comment by msphan** [comment]
Hi @hoerldavid,

I've tested move tiles to grid in macro mode and it worked well now. Thank you for your nice fix :).

Son

**Comment by hoerldavid** [comment]
Hi @msphan & @alonyan ,

Sorry I forgot to mention this here, but batch mode loading tile locations from files has been added for some time now (https://github.com/PreibischLab/BigStitcher/commit/060176f947b2358855c9fb60d253e0614a1a1904). You can find it in the Fiji menu at **Plugins>BigStitcher>Batch Processing>Tools,->Load TileConfiguration from File...**

Since this is implemented and your original problem seems to be fixed @msphan , I'll close this.

Best,
David
