### ISSUE TITLE
Problem turning on RegistrationExplorer

### ISSUE THREAD

**Issue by ptillberg** [PreibischLab/BigStitcher#18]
If I turn on RegistrationExplorer, then switch to Stitching mode and back to Multiview mode, I cannot turn on Registration Explorer again. There are no error messages--it just doesn't launch. Closing and re-opening BigStitcher does not help. I have to close and re-open ImageJ before I can re-launch RegistrationExplorer. I am able to turn RegistrationExplorer on and off repeatedly if I do so without leaving Multiview mode.

**Comment by StephanPreibisch** [comment]
Hi @ptillberg, I also experienced that, but only on Linux and could so far not reproduce it. I think this might be related to javafx @hoerldavid used to implement it. Do you also use Linux?

**Comment by ptillberg** [comment]
Hi Stephan and David,

I am running Windows 7 Professional. My Java version is 1.8.0_171. Not sure
if that helps--let me know if there's any other information you need!

-Paul

**Comment by hoerldavid** [comment]
Hi @ptillberg & @StephanPreibisch,

I could reproduce the bug on my Mac as well and I think I found the solution:
https://github.com/PreibischLab/multiview-reconstruction/commit/5bfa64f91dc1bcd4bd74e1bb81a0db38e44e0ee2

As suspected, JavaFX is the culprit: When we first open the registration explorer, the JFX platform is initialized and once we switch the mode, it is **implicitly shut down** because all parent UI elements are closed. Apparently, one cannot restart it once it has terminated and trying to open the registration explorer again will cause a deadlock in that thread (for the user, it looks as if nothing happens at all). 

There is the option of turning off the implicit shutdown and that solves the problem for me.
Let me know if solves the problem for you as well.

Best,
David
