### ISSUE TITLE
surrounding views don't show up when manually translating view

### ISSUE THREAD

**Issue by StephanJanosch** [PreibischLab/BigStitcher#25]
I found an issue. 

The surrounding views don't show up when I want to translate a single view. They only show up when I want to translate more than one view. Check out the video: https://cloud.mpi-cbg.de/index.php/s/XnaCBDsBIJoL0yY

I basically learned how to use this feature during the 5 minutes of the video. I did not read the manual properly. That's why the video is a bit long. ;-)

**Comment by hoerldavid** [comment]
Hi @StephanJanosch,

This problem should have been fixed with 8d74acd9d5964a0c01da087c874fba8a914536fe.

On a side note, you do not have to close the "Move Views" dialog every time you wish to move different images. You can just select new images in the main widow (you will be asked whether to keep or discard the transformation of currently selected images): https://cloud.bio.lmu.de/index.php/s/k7pxA3oQr8EJa6q

Best,
David
