### ISSUE TITLE
Automation Question

### ISSUE THREAD

**Issue by jdp-cshl** [PreibischLab/BigStitcher#32]
Hi - I am attempting to automate the Big Stitching plugin by getting window handles on each of the screens, setting the values I need, and clicking OK from code.  I have been able to do this until I get to the screen titled "Regular Grid Options" which allows the user to choose tile configurations.

What is the class for this window?  Is there an existing way I can hook into it to set its values from code?

Thank you.

**Comment by hoerldavid** [comment]
Hi @jdp-cshl,

Sorry for getting onto this so late.
I don't know if this issue is still relevant to you or it was solved by our email exchange in the meantime?

Our default way of automating BigStitcher is via ImageJ macros. We have added some documentation about how to do it to the ImageJ wiki: https://imagej.net/BigStitcher_Headless

Regarding the grid question:
The class responsible for the regular grid window is: https://github.com/PreibischLab/BigStitcher/blob/master/src/main/java/net/preibisch/stitcher/gui/PreviewRegularGridPanel.java

It is not really designed to be controlled from code, however.
https://github.com/PreibischLab/multiview-reconstruction/blob/master/src/main/java/net/preibisch/mvrecon/fiji/datasetmanager/grid/RegularTranformHelpers.java (in the multiview-reconstruction repo) contains code on how to query grid parameters in a macro-compatible way and apply them to a dataset.

Anyway, I'll close this for now, but if this is still a direction you're following (vs. macros), feel free to comment and I'll reopen the issue.

Best,
David
