### ISSUE TITLE
Intensity based weights in fusion

### ISSUE THREAD

**Issue by alonyan** [PreibischLab/BigStitcher#36]
Hi All,

We're trying to image very large samples, and so often we have parts of our image stacks that are significantly dimmer than others. 

Right now, during fusion, there is a pixel averaging step that leads to ugly dark stripes on our fused volumes. Is there a way, during the fusion step, to give the weights based on intensity? Even something like a max projection would probably work, or ideally some adjustable parameter.

Alternatively, is there an efficient way to normalize large amounts of images from many different stacks?

Thanks for the fantastic plugin!
Alon

**Comment by StephanPreibisch** [comment]
Hi @alonyan 

this functionality is already built in. You switch to multiview mode (on the top), then right click and select "Intensity Adjustments" and "Compute..." During the fusion/deconvolution step you can then use these adjustments.  The sliders define how much the intensity will be adjusted. "Offset" means to shift the intensities up & down, "scaling" means to multiply them with a factor. A combination of both is usually a good choice. The second slider regularizes how much it is changed at all since an optimal solution would be to scale all intensities to 0 ... so this trivial solution must be avoided. Let me know how that works for you.

**Comment by StephanPreibisch** [comment]
Hi, this is weird, maybe the amount of pixels in the overlap regions is bigger than we usually experience. Maybe you could try to start with way more significant downsampling (40x?) and see if that works for you. If the overlap is big, more downsampling should work just fine.

**Comment by alonyan** [comment]
Hi, 
So I managed to get it to work on a smaller subset of the data, but then realized this was not exactly what I had in mind since it calculates an adjustment for the whole view setup.  During fusion, are the weights applied to each pixel? or to the whole setup ID?

I'll try to illustrate our issue:
![spimbrightnessissues](https://user-images.githubusercontent.com/22939455/51632195-91068f80-1f03-11e9-97e6-cfc04cfbd98a.png)
So within one tile, we need to normalize the brightness of some of the Z slices. 

Alternatively, during fusion, the dim regions correspond to bright regions on another tile, so a max-fusion would do the trick if the weights are per-pixel (even a downsampled pixel), but probably wont work if they are per-setup.

Does this make any sense? I'm not sure if I'm explaining myself very well.

Thanks again!
Alon
