### ISSUE TITLE
loading Micromanager2 data

### ISSUE THREAD

**Issue by pawlowska** [PreibischLab/BigStitcher#37]
I acquire images using Micromanager2. The data format is 1 channel, many tiles, filenames in name_Pos**.ome.tif format. There are two issues:
1) minor: for correct loading, one has to choose Series=Tiles, Filename pattern=ignore, which is confusing
2) less minor: autoloader reads metadata wrongly. In my data, X is decreasing and this is not recognised, see screenshots - first is from Autoloader, second is a result of defining grid manually. In this dataset, defining the grid manually is not such a big deal, but in general, this means that you have to remember whether it was 3x4 or maybe 4x3 tiles, how much overlap etc.
I can provide this dataset via Google Drive or something if this helps.
![2_pattern](https://user-images.githubusercontent.com/11158300/52343959-d81f7500-2a19-11e9-99d3-228565241d6b.PNG)
![3_metadata](https://user-images.githubusercontent.com/11158300/52343961-d950a200-2a19-11e9-8116-0313848c274a.PNG)
![4_manual](https://user-images.githubusercontent.com/11158300/52343965-da81cf00-2a19-11e9-9ddf-4a660347f9cb.PNG)

**Comment by hoerldavid** [comment]
Hi @pawlowska,

Regarding 1: I agree that this is confusing.
* I think this can be fixed by looking for patterns only in files that were no already "grouped" by BioFormats. I will look into this.
* On a side note, asking whether the 1 channel is a channel or an illumination is needlessly confusing as well (as all images will be channel1, illumination1 anyway). We might get rid of the query in this case...

Regarding 2: This is indeed an annoying problem that I encountered as well for different scopes. It might not be possible to solve automatically though, since we typically have **no metadata telling us the direction of the axes**.

I'm thinking about adding a simple "Flip axes" option to BigStitcher, e.g. in the main menu under **Arange views**, so the user could fix this problem with a few clicks after creating the dataset. What are your thoughts on this @StephanPreibisch ?

Anyway, since I have no real MM dataset of my own lying around, it would be great if you could provide the 4 tiles shown here @pawlowska . Thanks in advance!  

Best,
David

**Comment by hoerldavid** [comment]
Hi @pawlowska,

Just a short update on the issue:
* I added a fix for problem 1: https://github.com/PreibischLab/multiview-reconstruction/commit/e8e33206c92d17fb4c0ec5356be7158d58cac7bf. If patterns are already handled by Bioformats (e.g. MM ```name_Pos**.ome.tif```), they are no longer shown in the pattern assignment section:

E.g.: for some files Test*(not grouped by Bioformats)_1_MMStack_Pos*(grouped as Tiles by BF).ome.tif:
![screenshot 2019-02-27 at 12 46 43](https://user-images.githubusercontent.com/3527592/53488159-c582e380-3a8d-11e9-80b1-ef89fb0f0e74.png)

* Furthermore, I also implemented the quick image flipping I mentioned earlier (https://github.com/PreibischLab/BigStitcher/commit/b5b5f8f4eab2bb093e12a8408459e2902fd53909) - that should take care of the ambiguous axis directions: 

![untitled-1](https://user-images.githubusercontent.com/3527592/53493348-6e840b00-3a9b-11e9-8ae4-a1738c2a185f.png)

We will merge it into the next release of BigStitcher/multiview-reconstruction. Hopefully, this will take care of your problems.

Best,
David

**Comment by pawlowska** [comment]
this should help, I'm looking forward to trying it

**Comment by pawlowska** [comment]
@hoerldavid it seems that I forgot to share the data with you. Here it is:
https://drive.google.com/open?id=1Dud5xE25WVXPHm_y8wfaAZzfE5tRJ0qY

**Comment by hoerldavid** [comment]
Hi @pawlowska,

Just wanted to let you know that the fixes should now be included in the main version of BigStitcher.

I think this solves this issue, so I will close it. If you are still experiencing problems, feel free to comment here and I will re-open it.

Best,
David
