### ISSUE TITLE
data stored on server cannot be saved in windows

### ISSUE THREAD

**Issue by lacan** [PreibischLab/BigStitcher#54]
Opening a dataset from a Windows server works no problem but when it comes to resaving data, we've encountered some issues:
![image](https://user-images.githubusercontent.com/319932/62195696-d4432e80-b37c-11e9-9c33-00a73ed4504a.png)
with the error `Failed to save XML '/128.178.193.33/FishData/OatesLab/Rachna/BIOP_20170731/20190715_e1_F_20-6/20190715_fss_e1_F_20-6_1.xml': mpicbg.spim.data.SpimDataIOException: java.io.FileNotFoundException: \128.178.193.33\FishData\OatesLab\Rachna\BIOP_20170731\20190715_e1_F_20-6\20190715_fss_e1_F_20-6_1.xml (The system cannot find the path specified)`

It seems that the first backslash is escaped (should be `\\`)

Thanks for any help
Oli

**Comment by hoerldavid** [comment]
Hi @lacan 

This has been a recurring problem in BigStitcher (https://github.com/PreibischLab/BigStitcher/issues/29, https://github.com/PreibischLab/multiview-reconstruction/issues/14). The quickest solution would be to mount the share to a drive letter (using **Map network drive** in Explorer).

Since this is the third time this problem has come up, and I have a working solution for volumes not mounted as a drive letter already (https://github.com/PreibischLab/multiview-reconstruction/issues/14), I will just add that in the next update. Do you have any objections @StephanPreibisch ?

Best,
David

**Comment by hoerldavid** [comment]
Hi @lacan,

I commited the fix (https://github.com/PreibischLab/multiview-reconstruction/commit/688df4ea4427899abe6136457e58250846154832), it will be included in the next update.

Cheers,
David
